### GENERAL SETTINGS ###

# Site settings
title: GovWizely
description: "GovWizely helps government agencies build applications with their data. We bring modern technologies to government projects and work with our clientele to fight bureaucratic roadblocks."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#1d7296" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#FFFFF" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#384452"
  footer_content: "#384452"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - GovWizely, LLC
    - 10523-A Braddock Road
    - Fairfax VA 22032
    - United States.
email: info@govwizely.com
tel: 703.995.9913


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Erik Arnold
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:erik@govwizely.com
      - title: twitter
        url: http://twitter.com/handle
  - name: James Issacs
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Tim Hammer
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: AJ Singh
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: GSA
    img: gsa.png
  - name: ITA
    img: ita.png
  - name: FTC
    img: ftc.png
  - name: SUSA
    img: susa.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "GovWizely helps government agencies build applications with their data. We bring modern technologies to government projects and work with our clientele to fight bureaucratic roadblocks."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Stuart Ridgway
    position: UX Lead - company
